# logo
favicon:
  logo: 
  icon16: 
  icon32: 
  apple_touch_icon: 
  webmanifest: 
  visibilitychange: true
  hidden: failure.ico
  show_text: 回来啦~
  hide_text: (●—●)看不见我！

top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
    children:
      - title: 标签
        url: /tags/
      - title: 分类
        url: /categories/
  - title: menu.links
    url: /links/
  - title: menu.about
    url: /about/
		noswup: true

sidebar:
  typedTextPrefix: 一个  
  typedText: [ '平凡的码农' ]
  info: 
    - key: 居住地
      val: 无锡
    - key: 码龄
      val: 7
  social:
    - icon: fas fa-rss
      url: atom.xml
    - name: Github
      icon: fab fa-github
      url: https://github.com/DraceWang
    - name: facebook
      icon: fab fa-facebook
      url: https://www.facebook.com/profile.php?id=100006615107136
    - name: weibo
      icon: fab fa-weibo
      url: https://www.weibo.com/u/2421168192
    - name: ZhiHu
      icon: fab fa-zhihu
      url: https://www.zhihu.com/people/wang-shun-da-55

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyright_year: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 10/08/2023 10:00:00
  custom_text:

search:
  enable: true
  type: local
  preload: true
  trigger: auto

baidu_push: true

reward:
  enable: false
  methods:
    - name: 微信
      path: https://mp-8b005489-7724-4f8c-afdd-30192ff4f7ae.cdn.bspapp.com/cloudstorage/61a57135-2e65-4d51-8be1-03b8bd1c595e.jpg
    - name: 支付宝
      path: https://mp-8b005489-7724-4f8c-afdd-30192ff4f7ae.cdn.bspapp.com/cloudstorage/a21e9954-22f2-43fe-b3b0-3dba1fdde3ed.jpg
    - name: QQ
      path: https://mp-8b005489-7724-4f8c-afdd-30192ff4f7ae.cdn.bspapp.com/cloudstorage/69fb1903-d0dc-4169-9a02-1e76ec8e7761.jpg

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

swup: true

toc:
  enable: true
  list_number: true
  max_depth: 6
  min_depth: 1

rightside:
  readmode: true
  aside: true

post_pagination: 
  enable: true 
  type: small

cdn:
  js:
    head:
    base: [demo.js]

assets:
  third_party_provider: unpkg

highlight:
  title: default
  height_limit: 200

theme: 
  switch: true
  default: auto

cover:
  default: 
    - /img/block.jpg
    - https://img2.wallspic.com/previews/7/6/8/1/7/171867/171867-wu_kong-chao_ji_sai_ya_ren-sai_ya_ren-zamasu-long_zhu-500x.jpg
    - https://img3.wallspic.com/previews/2/0/1/8/6/168102/168102-yi_shu-ka_tong-mian_bu_biao_qing-kuai_le_de-ji_qie-500x.jpg
    - https://img2.wallspic.com/previews/2/6/4/3/7/173462/173462-qi_fen-zi_se_de-zi_ran_jing_guan-yu_hui-de_ping_xian-500x.jpg
    - https://img2.wallspic.com/previews/3/3/9/1/3/131933/131933-mo_xing-xiao_jie-huang_se_de-nu_hai-fa_xing-500x.jpg
    - https://img1.wallspic.com/previews/8/3/4/6/2/126438/126438-wei_lai_zhu_yi-shu_ma_yi_shu-jie_duan-zi_ben_shi-yi_shu-500x.jpg
    - https://img2.wallspic.com/previews/0/1/5/0/7/170510/170510-guang-azure-zi_se_de-zi_ran_huan_jing-zi_ran_jing_guan-500x.jpg
    - https://img2.wallspic.com/previews/3/6/9/6/5/156963/156963-yi_shu-qi_fen-yu_hui-shou_shi-ren_men_zai_zi_ran_jie-500x.jpg
    - https://img1.wallspic.com/previews/0/9/3/5/6/165390/165390-qi_fen-zi_se_de-zi_ran_huan_jing-zi_ran_jing_guan-tian_wen_xue_dui_xiang-500x.jpg
    - https://img3.wallspic.com/previews/2/8/6/1/7/171682/171682-yi_kuai-xing_zhi-ye_ti-yi_shu-shui_xia-500x.jpg
    - https://img1.wallspic.com/previews/7/1/9/9/89917/89917-bo_xi_ta_nuo-an_zhuang_de_feng_jing-cheng_shi-suo_lun_tuo-shan_zhan-500x.jpg  
    - https://img1.wallspic.com/previews/6/2/3/5/6/165326/165326-pang_ke2077-pang_ke-qi_fen-xing_zhi-zi_se_de-500x.jpg
    - https://img2.wallspic.com/previews/8/9/4/5/6/165498/165498-ka_tong-tao-pin_hong_se-zhang_zhang_de_tou_fa-ji_qie-500x.jpg
    - https://img3.wallspic.com/previews/5/7/4/2/7/172475/172475-yi_shu-tao-tou_fa-ka_tong-500x.jpg  
    - https://img2.wallspic.com/previews/5/0/9/0/70905/70905-hai_yang-ma_er_dai_fu-tian_kong-du_jia_cun-huan_jiao-500x.jpg  
    - https://img3.wallspic.com/previews/4/3/4/8/6/168434/168434-xing_zhi-zi_ran_jing_guan-dan_huang-shui_dao-zhi_bei-500x.jpg
    - https://img2.wallspic.com/previews/6/5/4/5/6/165456/165456-giy_fu_gang-e_mo_sha_shoukimetsu_no_yaiba-shan_zi_de_yi_shu-zi_se_de-dian_lan_se_de-500x.jpg
    - https://img1.wallspic.com/previews/5/4/0/4/7/174045/174045-jian_ying-qi_fen-ren_men_zai_zi_ran_jie-tian_wen_xue_dui_xiang-yi_shu-500x.jpg
    - https://img1.wallspic.com/previews/9/3/1/6/5/156139/156139-feng_jing_hua-yi_shu-shu_ma_yi_shu-qi_fen-sheng_tai_qu-500x.jpg
    - https://img2.wallspic.com/previews/7/6/4/5/7/175467/175467-wo_de_xue_shu_jie_de_ying_xiong-tao-yi_shu-ka_tong-azure-500x.jpg
    - https://img1.wallspic.com/previews/3/7/0/0/7/170073/170073-liang_ge_ling-ka_tong-shou_shi-chuang_zao_xing_de_yi_shu-hong_se_de-500x.jpg
    - https://img1.wallspic.com/previews/1/8/3/6/6/166381/166381-shi_zi-xin_ba-bai_se_shi_zi-hu_xu-mao_ke-500x.jpg
    - https://img3.wallspic.com/previews/4/2/2/3/7/173224/173224-ri_luo-shui_zi_yuan-qi_fen-yu_hui-zi_se_de-500x.jpg
    - https://img1.wallspic.com/previews/7/5/7/9/6/169757/169757-ji_bo_li_de_bo_wu_guan-zi_ran_jing_guan-yi_shu-ji_yun-500x.jpg  
    - https://img1.wallspic.com/previews/5/2/0/6/7/176025/176025-qi_fen-tian_wen_xue_dui_xiang-yi_shu-dian_lan_se_de-yuan_quan-500x.jpg
    - https://img3.wallspic.com/previews/6/5/8/1/4/141856/141856-hen_ku_de-hui_hua-yu_yan_jing_tou-zhai_nan-tu_xing_she_ji-500x.jpg
    - https://img1.wallspic.com/previews/2/1/6/5/6/165612/165612-kimetsu_no_yaiba-e_mo_sha_shoukimetsu_no_yaiba-tao-tou_fa-wai_tao-500x.jpg
    - https://img3.wallspic.com/previews/5/1/0/2/4/142015/142015-feng_ge-ka_ka_xi_qi_mu-huo_ying_ren_zhe-tu_xing_she_ji-shi_jue_yi_shu-500x.jpg
    - https://img1.wallspic.com/previews/8/8/7/8/5/158788/158788-e_mo_sha_shoukimetsu_no_yaiba-shnen_man_hua-tao-ka_tong-azure-500x.jpg
  type: random

# layout:
#   footer: async/footer
#   page_loading: async/page-loading
#   post_card: async/post-card
#   fixed_btn: async/fixed-btn
#   header_search: async/empty

banner:
	danmu: 
		enable: false
		avatar: false
		delayRange: 5000
		speed: 80
  default:
    type: img
    bgurl: /img/banner.png
    banner_text: Hi my new friend!
    position: top
    fit: cover
  index:
    type: video
    bgurl: /video/banner4index4.mp4
    banner_title: 江湖险恶，<br>不行就撤。
    banner_text: Hi my new friend!
    videoUrl: 
  archive:
    banner_title: 吾日三省吾身，<br>关吾什么屁事
    banner_text: The article archive
  links:
    banner_title: 莫愁前路无知己，<br>天下谁人不识君。
    banner_text: A link to a friend's website
  tags:
    banner_title: 何以解忧，<br>唯有退休。
    banner_text: The tags cloud
  comment:
    banner_title: 
    banner_text: The magic tree hole
  about:
    type: video
    bgurl: /video/banner4about.mp4
    banner_title: 枯藤老树昏鸦，<br>摸鱼然后回家。
    banner_text: About me

# User info
user:
  name: Drace Wang
  first_name: Wang
  last_name: Drace
  email: wsdboy007@163.com
  domain: https://dracewag.github.ico
  avatar: /img/avatar.jpg
  describe: 
  rule_text: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

# About page settings
about:
  title: 解决问题，你想各种办法，解决一个问题，然后接着解决下一个问题，循环往复，等你解决了足够多的问题，你就可以回家了。</br> You do the math. You solve one problem then you solve the next one. And then the next. And if you solve enough problems, you get to come home.</br><div align="right" >——《火星救援》</div>
  introduction: 大家好，我是 <strong>Drace Wang</strong>，很高兴您能在浩瀚如烟的互联网世界里发现这个博客，更感谢您能够饶有兴致地浏览这个页面。建立这个 Blog 是出于兴趣爱好，我将在此分会分享一些学习笔记，可能还会分享少许图片、视频以及其他有趣东西的链接。
  blog: 
    <ul class="trm-list">
      <li>程序：Hexo </li>
      <li>主题：Hexo-theme-async </li>
    </ul>
  privacy: 
   
# Post wordcount
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: true
  count: true
  time: true

web_analytics:  
  enable: true 
  baidu: 16cea90ac06537b0a37ea52df3d2ede6
  google: G-T84GJPQD33
